### ISSUE TITLE
Recommendation for the "Contact Me" form.  

### ISSUE THREAD

**Issue by ghost** [PenetratingShot/csp#1]
If you want your contact form to work but still be hosted on GitHub pages rather than using NodeJS or php hosting you should create a separate server and host it on a machine and then post to that server.

e.g.

You could have your form in the html look like this:

```html
<form action="http://serverip:serverport/url-endpoint" method="post">
...
</form>
```

Then in your backend server, you could use NodeJS to handle the post data like this:

```javascript
const express = require('express');
const app = express();
const port = 'someportnumber';

app.use(express.urlencoded())

app.post('/url-endpoint', (req, res) => {
  // the data1 and data2 variables are examples of what your names of your form `<input>`s could be.
  const data1 = req.body.data1;
  const data2 = req.body.data2;

  // Now that you have the data you could use the `fs` module to put the data in a json file and have it saved, or you could use mongoose and us mongodb to save the data (this data is pretty simple so it wouldn't make sense to use mongodb but still and option).
}) 

app.listen(port, () => {
  console.log(`Listening on port ${port}`)
})
```

IDK just a suggestion, hope this helps.

*you need to port forward your server if you are hosting it on your own machine.

**Comment by shreyaslad** [comment]
This is actually for a CS class, idk why they used php :/

I don't need the form to work, I just need it to look pretty, but thanks :)

**Comment by ghost** [comment]
Yeah np.

**Comment by shreyaslad** [comment]
I might look into doing this but in another language

Thanks :)

**Comment by ghost** [comment]
yw
